
platform :ios, '12.0'

target 'AppHarbrDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppHarbrDemoApp
  pod 'AppLovinSDK', '11.4.3'

  #AppLovin Max Adapter
  pod 'AppLovinMediationAdColonyAdapter', '4.8.0.0.0'
  pod 'AppLovinMediationChartboostAdapter', '8.5.0.3'
  pod 'AppLovinMediationFacebookAdapter', '6.9.0.9'
  pod 'AppLovinMediationFyberAdapter', '8.1.3.2'
  pod 'AppLovinMediationGoogleAdManagerAdapter', '9.1.0.0'
  pod 'AppLovinMediationGoogleAdapter', '9.1.0.0'
  pod 'AppLovinMediationInMobiAdapter', '10.0.2.1'
  pod 'AppLovinMediationUnityAdsAdapter', '4.0.1.2'
  pod 'AppLovinMediationVungleAdapter', '6.11.0.1'
  pod 'AppLovinMediationIronSourceAdapter'

  #AppHarbr SDK
  pod 'AppHarbrSDK', '1.5.5'

end
