
platform :ios, '12.0'

target 'AppHarbrDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppHarbrDemoApp
  pod 'AppLovinSDK', '12.6.0'

  #AppLovin Max Adapter
  pod 'AppLovinMediationChartboostAdapter', '9.7.0.1'
  pod 'AppLovinMediationFacebookAdapter', '6.15.2.0'
  pod 'AppLovinMediationFyberAdapter', '8.3.1.1'
  pod 'AppLovinMediationGoogleAdManagerAdapter', '11.8.0.0'
  pod 'AppLovinMediationGoogleAdapter', '11.8.0.0'
  pod 'AppLovinMediationInMobiAdapter', '10.7.5.0'
  pod 'AppLovinMediationUnityAdsAdapter', '4.12.2.0'
  pod 'AppLovinMediationVungleAdapter', '7.4.0.0'
  pod 'AppLovinMediationIronSourceAdapter', '8.2.0.0.0'

  #AppHarbr SDK
  pod 'AppHarbrSDK', '1.16.0'

end
