
platform :ios, '12.0'

target 'AppHarbrDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppHarbrDemoApp
  pod 'Google-Mobile-Ads-SDK'

  #AdMob Adapter

  pod 'GoogleMobileAdsMediationUnity'
  pod 'GoogleMobileAdsMediationFyber'
  pod 'GoogleMobileAdsMediationInMobi'
  pod 'GoogleMobileAdsMediationChartboost'
  pod 'GoogleMobileAdsMediationFacebook'
  pod 'GoogleMobileAdsMediationAppLovin'
  pod 'GoogleMobileAdsMediationIronSource'
  pod 'GoogleMobileAdsMediationVungle'
  pod 'GoogleMobileAdsMediationAdColony'

  #AppHarbr SDK
  pod 'AppHarbrSDK'

end
